// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using brane;

namespace braneTwo.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20210302154257_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("brane.Models.ExigenceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("JalonId")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("TaskItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JalonId");

                    b.HasIndex("TaskItemId");

                    b.ToTable("ExigenceItems");
                });

            modelBuilder.Entity("brane.Models.JalonItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AssigneeId")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("PlannedStartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("RealEndDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.ToTable("JalonItems");
                });

            modelBuilder.Entity("brane.Models.ProjectItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AssigneeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.ToTable("ProjectItems");
                });

            modelBuilder.Entity("brane.Models.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AssigneeId")
                        .HasColumnType("int");

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("JalonItemId")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("Planned_start_date")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Real_start_date")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("JalonItemId");

                    b.ToTable("TaskItems");
                });

            modelBuilder.Entity("brane.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("brane.Models.ExigenceItem", b =>
                {
                    b.HasOne("brane.Models.JalonItem", "Jalon")
                        .WithMany()
                        .HasForeignKey("JalonId");

                    b.HasOne("brane.Models.TaskItem", null)
                        .WithMany("Exigences")
                        .HasForeignKey("TaskItemId");

                    b.Navigation("Jalon");
                });

            modelBuilder.Entity("brane.Models.JalonItem", b =>
                {
                    b.HasOne("brane.Models.User", "Assignee")
                        .WithMany()
                        .HasForeignKey("AssigneeId");

                    b.Navigation("Assignee");
                });

            modelBuilder.Entity("brane.Models.ProjectItem", b =>
                {
                    b.HasOne("brane.Models.User", "Assignee")
                        .WithMany()
                        .HasForeignKey("AssigneeId");

                    b.Navigation("Assignee");
                });

            modelBuilder.Entity("brane.Models.TaskItem", b =>
                {
                    b.HasOne("brane.Models.User", "Assignee")
                        .WithMany()
                        .HasForeignKey("AssigneeId");

                    b.HasOne("brane.Models.JalonItem", null)
                        .WithMany("Tasks")
                        .HasForeignKey("JalonItemId");

                    b.Navigation("Assignee");
                });

            modelBuilder.Entity("brane.Models.JalonItem", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("brane.Models.TaskItem", b =>
                {
                    b.Navigation("Exigences");
                });
#pragma warning restore 612, 618
        }
    }
}
